# Generated by Django 3.2.5 on 2022-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDistance', models.CharField(max_length=60)),
                ('totalDurationInMin', models.FloatField()),
                ('bounds', models.CharField(max_length=60)),
                ('polylinePoints', models.CharField(max_length=60)),
            ],
        ),
    ]
