name: "build"
on:
    release:
        types: [published]
    workflow_dispatch:
jobs:
    build:
        name: "Linux Build" 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Flutter
              uses: subosito/flutter-action@v2
            - name: Build
              run: |
                    sudo apt-get update -y
                    sudo apt-get install -y ninja-build libgtk-3-dev
                    flutter config --enable-linux-desktop
                    flutter build linux
                    flutter build web
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                name: linux
                path: |
                    build

    windowsBuild:
        name: "Windows Build" 
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Flutter
              uses: subosito/flutter-action@v2
            - name: Build
              run: |
                    flutter config --enable-windows-desktop
                    flutter build windows
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                name: windows
                path: |
                    build
    macOSBuild:
        name: "OSX Build" 
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                architecture: x64
            - name: Build
              run: |
                    flutter build ios --release --no-codesign
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                name: iOS
                path: |
                    build