name: "Test"
on:
    push:
    workflow_dispatch:
jobs:
    build:
        name: "Test" 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Flutter
              uses: subosito/flutter-action@v2
            - name: Test
              run: |
                    flutter pub get
                    flutter test